# Name of the project
PROJECT_NAME = TOURISM_MANAGEMENT_SYSTEM

#Doxyfile folder
DOC = documentation

#All source code files
SRC = main.c\
src/main_operations.c

#All test source files
TEST_SRC = src/tour_operations.c\
test/test_tour_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = tour.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html
Build:
	gcc function.c test_tourism.c unity/unity.c -Iunity
Run:
	./a.out	

